version: '3.9'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ivietl
      POSTGRES_DB: pb_dw

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports: 
      - 8080:8080